# Generated by Django 3.0 on 2020-07-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched_Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, null=True)),
                ('symptom', models.TextField(null=True)),
                ('date1', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Doctor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Patient')),
            ],
        ),
    ]
