# Generated by Django 3.0 on 2020-07-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_searched_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='searched_patient',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Type'),
        ),
    ]
