# Generated by Django 3.0 on 2020-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_searched_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='searched_symptom',
            name='name1',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
