# Generated by Django 3.0 on 2020-07-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_searched_symptom_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searched_patient',
            name='symptom',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
