# Generated by Django 3.0 on 2020-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20200727_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='searched_symptom',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
