# Generated by Django 3.0 on 2020-07-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20200727_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='searched_symptom',
            name='name2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
